### ISSUE TITLE
Getting error Assertion failed

### ISSUE THREAD

**Issue by mwoodpatrick** [NVIDIA/libnvidia-container#73]
When running in my environment, I'm getting:
```
time="2019-12-10T04:48:07-08:00" level=debug msg="[hijack] End of stdout"                                                                                       
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: Assertion failed ([REDACTED], line 3180): condition 0 not true\\\\nnvidia-container-cli: initialization error: driver error: failed to process request\\\\n\\\"\"": unknown.         
```

It appears that the build of nvidia container puts the debug information in a separate file in:

         /usr/local/lib/debug/usr/local/lib/libnvidia-container.so.1

When grabbing the process nvc:[driver] and using the gdb command:

     set debug-file-directory /usr/local/lib/debug/usr/local/lib

I'm still not seeing symbols in the function nvc_init please advise as to what is needed to view symbols in /usr/local/lib/libnvidia-container.so.1? 

I'm running with gdb version "GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git" on Ubuntu 18.04.3 LTS.

#0  0x00007f3baaf99bc4 in __GI___poll (fds=0x7ffce0027108, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f3baa864755 in ?? () from /usr/local/lib/libnvidia-container.so.1
#2  0x00007f3baa864b60 in ?? () from /usr/local/lib/libnvidia-container.so.1
#3  0x00007f3baa868522 in nvc_init () from /usr/local/lib/libnvidia-container.so.1
#4  0x000055b9a036bc51 in ?? ()
#5  0x000055b9a036963b in ?? ()
#6  0x00007f3baaea6b97 in __libc_start_main (main=0x55b9a03695f0, argc=11, argv=0x7ffce0028758, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7ffce0028748) at ../csu/libc-start.c:310
#7  0x000055b9a036969a in ?? ()

**Comment by mwoodpatrick** [comment]
Running:

objdump -h /usr/local/lib/libnvidia-container.so.1.0.7 > $OUTPUT_DIR/ibnvidia-container.so.1.0.7.objdump

I see:

    .gnu_debuglink 00000020  0000000000000000  0000000000000000  000245c0  2**2
                  CONTENTS, READONLY

full output:

     /home/scratch.mwoodpatrick_inf/fsa/fsf_trees/Cuda_Test/444127733/output_12_11_19__0921/libnvidia-container.so.1.0.7.objdump

Running 

    objdump --debugging-tags -h /usr/local/lib/libnvidia-container.so.1.0.7 > $OUTPUT_DIR/libnvidia-container.so.1.0.7.objdump.tags

gives a bunch of messages of the form 

     objdump: Warning: There is a hole [0x28e86 - 0x28ec2] in .debug_loc section.


which appears
